pipeline:
  build:
    image: notnoopci/php:7.1-browsers
    volumes:
      - /tmp/composer-cache:/root/.composer/cache/
    commands:
      - cp .env.dusk .env
      - sudo composer install --ignore-platform-reqs
      - php artisan key:generate
      - touch database/database.sqlite
      - ./vendor/bin/phpunit
      - ./vendor/laravel/dusk/bin/chromedriver-linux &
      - php artisan serve &
      - php artisan dusk
