pipeline:
  build:
    image: notnoopci/php:7.1-browsers
    environment:
      - COMPOSER_CACHE_DIR=/cache
    volumes:
      - /tmp/composer-cache:/cache
    commands:
      - sudo apt-get update && sudo apt-get install -y libsqlite3-dev libzip-dev
      - sudo docker-php-ext-install gd zip
      - composer install --prefer-dist
      - cp .env.dusk .env
      - php artisan key:generate
      - touch database/database.sqlite
      - ./vendor/bin/phpunit
      - ./vendor/laravel/dusk/bin/chromedriver-linux &
      - php artisan serve &
      - php artisan dusk
