pipeline:
  build:
    image: notnoopci/php:7.1-browsers
    volumes:
      - /tmp/composer-cache:/root/.composer/cache/
    commands:
      - sudo apt-get update && sudo apt-get install -y libsqlite3-dev libzip-dev libpng12-dev
      - sudo docker-php-ext-install gd zip
      - sudo composer install --prefer-dist
      - sudo cp .env.dusk .env
      - sudo php artisan key:generate
      - sudo touch database/database.sqlite
      - sudo ./vendor/bin/phpunit
      - sudo ./vendor/laravel/dusk/bin/chromedriver-linux &
      - sudo php artisan serve &
      - sudo php artisan dusk
