git:
  submodules: false

language: php

cache:
  directories:
    - node_modules
    - $HOME/.composer/cache

php:
  - 7.0
  - 7.1

before_install:
  - phpenv config-rm xdebug.ini

install:
  - composer install --no-interaction --prefer-dist --no-suggest --no-scripts
  - composer run-script post-root-package-install
  - composer run-script post-create-project-cmd
  - composer run-script post-install-cmd
  - npm install
  - npm run dev

script: vendor/bin/phpunit

deploy:
  provider: heroku
  api_key:
    secure: hcBDjY6biPmHRTCW55uT/eI+8apYUdXJ91qjGQ8lWNFHwLcySzTKYCQblPBRF7Rc7Yhtx+HzaCuznpZJvyZ5D8dNafwEhpV6SJs28P99d7vNVNFzjGfWx/fTM20MKvH0i58LNAF7qjAe+PGyA5ceg4tRXVv3V/WJqLuo8vnO/isoiASiXuDXdG05ERvybFF1MbJIXSSPzo9ee963LaGmyajhy5tqlAvMan73EyKWvRQrqhmKf0IQaN2GCOIo32Tym90A5Q27PCvUXMtZqG9WeAK7Dj/wAUponQbqI2vZ89hfhoHsu7lw9g9XY/7pg3HghC2J8X9MvIm4fnnejDgu2hB6Q7wXhO90UXrhC4DpcwNuIESRwCEVwCOy9gPleOdBBcPIkul3lGew/E7wsvdieKZBIGlrwPZolvW+s/MTJKAipkabh+Xg4MneDYSeMWpRC89otobgfiKNd+HothHEKremO0VTX9a/+q8mCDtW/u/gzF6/dOVGtqlH6uEJBIsC+c7WhBCiMsk/huK9TQ73Qt49H/HPzO1ezTLaYdNWKm0D507ncAy1UCSqvyGdH+jPXRJye4IMlqs1RwzNHj/gK9egP5JrYCAltluPoxO2Rp0TwJXuYpJ8gNRVSVDcVR9oBsGJPr8QVC8fP9Df39gtMKQ5bE2OwwEBAbKNFxg/tcQ=
  app: laravel-boilerplate
  on:
    repo: adr1enbe4udou1n/laravel-boilerplate
    php: 7.1
  run:
    - "php artisan migrate --force"
    - "php artisan config:cache"
    - "php artisan route:cache"
    - "php artisan view:clear"
