git:
  submodules: false

language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.0
  - 7.1

matrix:
  fast_finish: true

install:
  - composer install --no-interaction --prefer-dist --no-suggest --no-scripts
  - composer run-script post-root-package-install
  - composer run-script post-create-project-cmd
  - composer run-script post-install-cmd

script: vendor/bin/phpunit
