version: 2
jobs:
  build:
    docker:
      - image: notnoopci/php:7.1-browsers

    steps:
      - checkout

      - run: cp .env.dusk .env

      - restore_cache:
          keys:
          - composer-v1-{{ checksum "composer.json" }}
          - composer-v1-

      - run: composer install -n --ignore-platform-reqs

      - save_cache:
          key: composer-v1-{{ checksum "composer.json" }}
          paths:
            - ./vendor

      - run: php artisan key:generate
      - run: touch database/database.sqlite
      - run: vendor/bin/phpunit

      - run:
          name: Start Chrome Driver
          command: ./vendor/laravel/dusk/bin/chromedriver-linux
          background: true

      - run:
          name: Run Laravel Server
          command: php artisan serve
          background: true

      - run:
          name: Run Laravel Dusk Tests
          command: php artisan dusk
